image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = true
  - ps: $env:NUGET_XMLDOC_MODE = "skip"
  - ps: $env:DOTNET_CLI_TELEMETRY_OPTOUT = 1
build_script:
  - dotnet --version
  - dotnet restore
  - dotnet build -c Release
  - dotnet pack -c Release .\GeographicLib\Sandwych.GeographicLib.csproj
artifacts:
  - path: '.\GeographicLib\**\*.nupkg'
deploy:
  - provider: NuGet
    on:
      branch: dev
    server: https://www.myget.org/F/maltreport/api/v2/package
    skip_symbols: true
    artifact: /.*\.nupkg/
  - provider: NuGet
    on:
      branch: master
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: NSw3haoScjXUkygtFw+GIiNd3i9C4+3xvGCaQM36iivZt6jnd+TmHQ8J0DcXe2Gh
    skip_symbols: true
    artifact: /.*\.nupkg/  
